#include<stdio.h>
#include<conio.h>
#include<graphics.h>

int Logo()
{
    
	textbackground(7);
    clrscr();
	gotoxy(12,5);textcolor(4);
    cprintf("     FFFFFFFFFFFFFFFFFFFF            GGGGGGGGGGGG         \n");
    gotoxy(12,6);textcolor(4);
    cprintf("     FF                            GG            GG       \n");
    gotoxy(12,7);textcolor(4);
    cprintf("     FF                          GG                GG     \n");
    gotoxy(12,8);textcolor(4);
    cprintf("     FF                        GG                         \n");
    gotoxy(12,9);textcolor(4);
    cprintf("     FF                        GG                         \n");
    gotoxy(12,10);textcolor(4);
    cprintf("     FF                        GG                         \n");
    gotoxy(12,11);textcolor(4);
    cprintf("     FFFFFFFFFFFFFFF           GG          GGGGGGGGGG     \n");
    gotoxy(12,12);textcolor(4);
    cprintf("     FF                        GG                  GG     \n");
    gotoxy(12,13);textcolor(4);
    cprintf("     FF                        GG                  GG     \n");
    gotoxy(12,14);textcolor(4);
    cprintf("     FF                          GG                GG     \n");
    gotoxy(12,15);textcolor(4);
    cprintf("     FF                            GG            GG       \n");
    gotoxy(12,16);textcolor(4);
    cprintf("     FF                              GGGGGGGGGGGG         \n");
    gotoxy(12,17);textcolor(4);
    cprintf("                                                          \n");
    gotoxy(12,18);textcolor(0);
    cprintf("     ------------------------------------------------     \n");
    gotoxy(12,19);textcolor(0);
    cprintf("                     FITNESS  GUIDER                      \n");
    gotoxy(12,20);textcolor(0);
    cprintf("     ------------------------------------------------     \n");
    


	return 0;
}